from .calendar import XNYSCalendar
from .epochs import EpochContext, EpochManager
from .identity import deduplicate_signals, event_key, execution_id, signal_id
from .health import classify_strategy_run
from .models import (
    LEGACY_SCHEMA_LABEL,
    METRIC_SCHEMA_VERSION,
    OUTCOME_WINDOWS,
    DeduplicationResult,
    Direction,
    EpochStatus,
    HealthStatus,
    MetricEpoch,
    OutcomeRecord,
    OutcomeStatus,
    PairedComparison,
    PortfolioMetrics,
    SignalConflict,
    SignalMetricRecord,
    StrategyHealthRecord,
)
from .store import MetricStore
from .service import MetricsService
from .outcomes import DirectionalAccuracy, OutcomeCalculator, directional_accuracy
from .portfolio import (
    DatedReturn,
    annualized_sharpe,
    daily_net_returns,
    drawdowns,
    equal_weighted_scenario_return,
    matched_benchmark_returns,
    matched_return,
    paired_comparison,
    portfolio_metrics,
    reconcile_costs,
    total_return,
    validate_snapshot_window,
)

__all__ = [
    "LEGACY_SCHEMA_LABEL",
    "METRIC_SCHEMA_VERSION",
    "OUTCOME_WINDOWS",
    "DeduplicationResult",
    "Direction",
    "DatedReturn",
    "EpochStatus",
    "EpochContext",
    "EpochManager",
    "HealthStatus",
    "MetricEpoch",
    "MetricStore",
    "MetricsService",
    "DirectionalAccuracy",
    "OutcomeCalculator",
    "OutcomeRecord",
    "OutcomeStatus",
    "PairedComparison",
    "PortfolioMetrics",
    "SignalConflict",
    "SignalMetricRecord",
    "StrategyHealthRecord",
    "XNYSCalendar",
    "deduplicate_signals",
    "daily_net_returns",
    "drawdowns",
    "equal_weighted_scenario_return",
    "event_key",
    "execution_id",
    "matched_benchmark_returns",
    "matched_return",
    "paired_comparison",
    "portfolio_metrics",
    "reconcile_costs",
    "directional_accuracy",
    "signal_id",
    "total_return",
    "validate_snapshot_window",
    "annualized_sharpe",
    "classify_strategy_run",
]
